
export const ALL_NFT_MARKET = 'ALL_NFT_MARKET'

//FILTROS
export const NFT_USER = 'NFT_USER'
export const NFT_BY_ID = 'NFT_BY_ID'
export const ORDER_NFT = 'ORDER_NFT'
export const ADD_NFT_FAVORITE = 'ADD_NFT_FAVORITE'
export const DELETE_NFT_FAVORITE = 'DELETE_NFT_FAVORITE'

//acciones
export const CREATE_NFT = 'CREATE_NFT'
export const EDIT_NFT_PRICE = 'EDIT_NFT_PRICE'
export const GIFT_NFT = 'GIFT_NFT'
export const BUY_NFT = 'BUY_NFT'
export const EDIT_NFT = 'EDIT'

//USER
export const RESET_ERROR_LOGUIN_USER='RESET_ERROR_LOGUIN_USER'
export const SEND_EMAIL_TO_RESET_PASSWORD= 'SEND_EMAIL_TO_RESET_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_ERROR = 'RESET_ERROR'
export const LOGUIN_USER = 'LOGUIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_TO_GOOGLE = 'GOOGLE_TO_GOOGLE'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const VALIDATE_USER = 'VALIDATE_USER'
